package javaHashSet;

import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution<T extends Serializable> {

    public static void main(String[] args) throws FileNotFoundException {
        Scanner s = new Scanner(new StringBufferInputStream("1000\n" +
                "ae ec\n" +
                "jl jj\n" +
                "gj ja\n" +
                "mc de\n" +
                "jc lj\n" +
                "ca mg\n" +
                "ni kg\n" +
                "cm id\n" +
                "an dd\n" +
                "if kj\n" +
                "nl ia\n" +
                "la el\n" +
                "ac gh\n" +
                "bh lc\n" +
                "ac im\n" +
                "nd ba\n" +
                "cm bl\n" +
                "bn fi\n" +
                "ik ia\n" +
                "kc mg\n" +
                "fi lk\n" +
                "nf mg\n" +
                "hc cl\n" +
                "fl me\n" +
                "jh cf\n" +
                "gh nl\n" +
                "bh lm\n" +
                "kn em\n" +
                "ff in\n" +
                "kf df\n" +
                "hm ab\n" +
                "kg gm\n" +
                "na dd\n" +
                "fk ad\n" +
                "de nh\n" +
                "dl fn\n" +
                "cn kj\n" +
                "fm mk\n" +
                "jc mm\n" +
                "gk jd\n" +
                "jf gd\n" +
                "bd ea\n" +
                "fk hc\n" +
                "ik aj\n" +
                "km ci\n" +
                "ib fb\n" +
                "be ld\n" +
                "nj ef\n" +
                "am ii\n" +
                "ba in\n" +
                "kn bf\n" +
                "ka ac\n" +
                "km jg\n" +
                "lc fe\n" +
                "fk gk\n" +
                "fj be\n" +
                "fe md\n" +
                "ea ae\n" +
                "nh jn\n" +
                "fi nj\n" +
                "ge nb\n" +
                "hm gb\n" +
                "gm lk\n" +
                "fk am\n" +
                "am nk\n" +
                "mi bd\n" +
                "cb cj\n" +
                "ic fh\n" +
                "hn jm\n" +
                "ll am\n" +
                "ii id\n" +
                "el nn\n" +
                "jj ke\n" +
                "dh ff\n" +
                "hd ad\n" +
                "ge jn\n" +
                "dj ln\n" +
                "hd lm\n" +
                "ln bn\n" +
                "kg mn\n" +
                "bh bd\n" +
                "ag id\n" +
                "in ef\n" +
                "da ea\n" +
                "jg le\n" +
                "jc ca\n" +
                "bm ne\n" +
                "ec dj\n" +
                "je me\n" +
                "kj fi\n" +
                "jc ne\n" +
                "cl ck\n" +
                "bn nl\n" +
                "bl mi\n" +
                "hn ma\n" +
                "cf jm\n" +
                "jd aj\n" +
                "mb dg\n" +
                "dj if\n" +
                "gn af\n" +
                "mk ai\n" +
                "il am\n" +
                "kg mb\n" +
                "lj lk\n" +
                "mj gh\n" +
                "id lj\n" +
                "mm al\n" +
                "ln af\n" +
                "jj li\n" +
                "ga ed\n" +
                "gm dd\n" +
                "id lc\n" +
                "lc he\n" +
                "fm nf\n" +
                "in be\n" +
                "me he\n" +
                "lc mi\n" +
                "am le\n" +
                "lc fh\n" +
                "em hd\n" +
                "ad fn\n" +
                "nd cf\n" +
                "dc jh\n" +
                "eh ln\n" +
                "hd hc\n" +
                "bj gi\n" +
                "lg nk\n" +
                "ed ln\n" +
                "eb me\n" +
                "cd hd\n" +
                "dg kd\n" +
                "nk dg\n" +
                "nm gh\n" +
                "ha bn\n" +
                "ef hc\n" +
                "ga ci\n" +
                "nd kk\n" +
                "eh lc\n" +
                "li fi\n" +
                "fe ml\n" +
                "ad ec\n" +
                "dh bf\n" +
                "mh hh\n" +
                "gh nc\n" +
                "kh kf\n" +
                "al fn\n" +
                "dd fk\n" +
                "hj hg\n" +
                "mi jh\n" +
                "bd kn\n" +
                "jd gl\n" +
                "kh lb\n" +
                "ak ee\n" +
                "fi dn\n" +
                "lc ji\n" +
                "jg nc\n" +
                "ad hh\n" +
                "fk ga\n" +
                "nh ja\n" +
                "ad nj\n" +
                "nb nn\n" +
                "jh me\n" +
                "hk lh\n" +
                "cb hc\n" +
                "en ja\n" +
                "jg mh\n" +
                "ng hg\n" +
                "kk nl\n" +
                "lg kh\n" +
                "nf kh\n" +
                "bf me\n" +
                "en gb\n" +
                "km nh\n" +
                "ei ad\n" +
                "mi jb\n" +
                "fh kg\n" +
                "ni aa\n" +
                "nd hl\n" +
                "he nm\n" +
                "dk nl\n" +
                "gd em\n" +
                "ll bk\n" +
                "dg jj\n" +
                "la ag\n" +
                "im hi\n" +
                "cf ff\n" +
                "ja dj\n" +
                "kh ek\n" +
                "ki gd\n" +
                "ff lf\n" +
                "lm mg\n" +
                "kg ni\n" +
                "eg cc\n" +
                "ji hg\n" +
                "ic nc\n" +
                "jd kd\n" +
                "lb ed\n" +
                "gg ia\n" +
                "ff gb\n" +
                "ji hn\n" +
                "mj ca\n" +
                "ee eh\n" +
                "gd hk\n" +
                "gd nn\n" +
                "dk cb\n" +
                "ag nh\n" +
                "jc jd\n" +
                "if df\n" +
                "mh dg\n" +
                "je nc\n" +
                "ik nn\n" +
                "am mm\n" +
                "gl md\n" +
                "bd ih\n" +
                "el kj\n" +
                "cb mm\n" +
                "ic fb\n" +
                "hm bc\n" +
                "jm bn\n" +
                "kh jj\n" +
                "de kd\n" +
                "ge ie\n" +
                "aj nk\n" +
                "kl ga\n" +
                "mb nd\n" +
                "ne ff\n" +
                "cl ci\n" +
                "fj bn\n" +
                "ai ai\n" +
                "ki kg\n" +
                "dg ak\n" +
                "ck la\n" +
                "je ba\n" +
                "if dh\n" +
                "cb nl\n" +
                "ki ih\n" +
                "ak ni\n" +
                "ek mk\n" +
                "dc hh\n" +
                "kg ff\n" +
                "kg dg\n" +
                "lm nf\n" +
                "lg an\n" +
                "ae fg\n" +
                "al aa\n" +
                "hb ie\n" +
                "bb ki\n" +
                "ia lm\n" +
                "gn cc\n" +
                "lf fb\n" +
                "lg bh\n" +
                "kl nj\n" +
                "gc hj\n" +
                "bh la\n" +
                "je gb\n" +
                "cn nb\n" +
                "mh bh\n" +
                "kj ih\n" +
                "nl ai\n" +
                "jj bi\n" +
                "jm bn\n" +
                "ee ni\n" +
                "gg jl\n" +
                "fl mi\n" +
                "ek bb\n" +
                "dh jb\n" +
                "di hb\n" +
                "bi hk\n" +
                "gj ji\n" +
                "lm dk\n" +
                "dd hd\n" +
                "bl li\n" +
                "fb id\n" +
                "il eg\n" +
                "ea hl\n" +
                "gd hd\n" +
                "kb ml\n" +
                "ln hf\n" +
                "ad ia\n" +
                "ab hn\n" +
                "ch df\n" +
                "dd mi\n" +
                "cj eh\n" +
                "kg ki\n" +
                "hl fe\n" +
                "kd jf\n" +
                "hk di\n" +
                "jl if\n" +
                "ch ll\n" +
                "ki ef\n" +
                "bf kk\n" +
                "lk fm\n" +
                "fk cf\n" +
                "nj in\n" +
                "gc ie\n" +
                "ld in\n" +
                "kn jn\n" +
                "fl de\n" +
                "cg bg\n" +
                "af ea\n" +
                "bj dg\n" +
                "el fm\n" +
                "lj bi\n" +
                "md ii\n" +
                "aj gg\n" +
                "gj if\n" +
                "na jh\n" +
                "di fm\n" +
                "bf cc\n" +
                "dn md\n" +
                "ge ka\n" +
                "fn jc\n" +
                "gd id\n" +
                "kd ik\n" +
                "bi di\n" +
                "ai gc\n" +
                "ld eb\n" +
                "an fa\n" +
                "bi bh\n" +
                "hc jg\n" +
                "dn hn\n" +
                "al jn\n" +
                "fl ha\n" +
                "df ce\n" +
                "gi fb\n" +
                "ha be\n" +
                "if li\n" +
                "hd mn\n" +
                "ce ki\n" +
                "bn hd\n" +
                "kd de\n" +
                "gm im\n" +
                "gm nm\n" +
                "nm dm\n" +
                "db ef\n" +
                "eb fi\n" +
                "fi ch\n" +
                "hl ie\n" +
                "md jb\n" +
                "bk nf\n" +
                "je dg\n" +
                "dg cg\n" +
                "hc le\n" +
                "cn lk\n" +
                "fl df\n" +
                "gd km\n" +
                "ej me\n" +
                "gj he\n" +
                "nk kn\n" +
                "cc fa\n" +
                "da fi\n" +
                "nh ed\n" +
                "cc id\n" +
                "fl ng\n" +
                "fc ii\n" +
                "li ml\n" +
                "en ii\n" +
                "nm je\n" +
                "ma ma\n" +
                "fk dj\n" +
                "mm mh\n" +
                "hg lc\n" +
                "ii km\n" +
                "ab hd\n" +
                "mg lc\n" +
                "cd gk\n" +
                "da ka\n" +
                "kg kj\n" +
                "cm ag\n" +
                "ce ik\n" +
                "ka gi\n" +
                "ni lk\n" +
                "nd mm\n" +
                "ec in\n" +
                "ci ah\n" +
                "mn ak\n" +
                "jj bb\n" +
                "mb jl\n" +
                "na fi\n" +
                "ib fl\n" +
                "eb jf\n" +
                "bb di\n" +
                "hm ac\n" +
                "ln mf\n" +
                "hn ee\n" +
                "ne bf\n" +
                "ec nk\n" +
                "ca hl\n" +
                "nd ag\n" +
                "el nb\n" +
                "jn dl\n" +
                "lf bf\n" +
                "dj he\n" +
                "le hc\n" +
                "he kc\n" +
                "el lj\n" +
                "bk ne\n" +
                "fg dd\n" +
                "fa nn\n" +
                "fj cc\n" +
                "el eg\n" +
                "cd ia\n" +
                "hn ch\n" +
                "il aj\n" +
                "ga lj\n" +
                "gk ll\n" +
                "km km\n" +
                "ib mn\n" +
                "mm gk\n" +
                "bk km\n" +
                "hd fg\n" +
                "bn cc\n" +
                "ae jh\n" +
                "al cg\n" +
                "jn ci\n" +
                "am gb\n" +
                "ig kk\n" +
                "bm ji\n" +
                "aa ag\n" +
                "ac ib\n" +
                "gg gm\n" +
                "dd cf\n" +
                "ad nl\n" +
                "ni mm\n" +
                "nb ii\n" +
                "mm aa\n" +
                "nn em\n" +
                "nb ll\n" +
                "hj hd\n" +
                "kg il\n" +
                "je ik\n" +
                "nb ij\n" +
                "cn bm\n" +
                "la ka\n" +
                "lh kk\n" +
                "im fi\n" +
                "ie mc\n" +
                "kd le\n" +
                "hh ne\n" +
                "ik le\n" +
                "ji aj\n" +
                "je hg\n" +
                "li de\n" +
                "hh le\n" +
                "lb en\n" +
                "ca bg\n" +
                "gf kj\n" +
                "bm mm\n" +
                "hn hk\n" +
                "dd ca\n" +
                "kn cm\n" +
                "ge cd\n" +
                "fn ac\n" +
                "ac if\n" +
                "hl ne\n" +
                "ji ci\n" +
                "he ea\n" +
                "id ai\n" +
                "af ee\n" +
                "jd ff\n" +
                "cn hn\n" +
                "bd ec\n" +
                "ah eg\n" +
                "nc ai\n" +
                "gh ie\n" +
                "kc mm\n" +
                "hf ci\n" +
                "ig nb\n" +
                "de al\n" +
                "ic le\n" +
                "hg ig\n" +
                "if mg\n" +
                "mi kn\n" +
                "ik jg\n" +
                "ba aa\n" +
                "eb bk\n" +
                "dc hi\n" +
                "ed kj\n" +
                "jm cl\n" +
                "dl de\n" +
                "fk bb\n" +
                "eg hm\n" +
                "gl kg\n" +
                "kh ci\n" +
                "jj an\n" +
                "mj jm\n" +
                "fl jh\n" +
                "ii jj\n" +
                "fa im\n" +
                "ge kj\n" +
                "bb nk\n" +
                "gd cj\n" +
                "mb ga\n" +
                "if mk\n" +
                "cl bm\n" +
                "fn hj\n" +
                "lb hi\n" +
                "fb cb\n" +
                "ba le\n" +
                "bf nf\n" +
                "fb fn\n" +
                "hi hl\n" +
                "fa jh\n" +
                "ah cj\n" +
                "if dj\n" +
                "fi ll\n" +
                "gm be\n" +
                "cb jh\n" +
                "aj eh\n" +
                "em ch\n" +
                "kb bh\n" +
                "je ci\n" +
                "hb eb\n" +
                "hk lk\n" +
                "jk aa\n" +
                "ji fl\n" +
                "dc cj\n" +
                "aa bh\n" +
                "bn nj\n" +
                "bh di\n" +
                "ih kj\n" +
                "de da\n" +
                "md mk\n" +
                "jf fh\n" +
                "ib an\n" +
                "bb eg\n" +
                "bf bb\n" +
                "md ja\n" +
                "kn jf\n" +
                "bb dm\n" +
                "cm gn\n" +
                "be em\n" +
                "en jj\n" +
                "bb ad\n" +
                "ea ea\n" +
                "di ad\n" +
                "fj gm\n" +
                "ia ig\n" +
                "kh dk\n" +
                "jb gk\n" +
                "nd dn\n" +
                "ff bm\n" +
                "dk mj\n" +
                "ca kf\n" +
                "hj bh\n" +
                "hm lb\n" +
                "fa kc\n" +
                "cn kn\n" +
                "dl kn\n" +
                "dh lg\n" +
                "dk ne\n" +
                "ii he\n" +
                "bf ja\n" +
                "dj bh\n" +
                "kd jh\n" +
                "cc gk\n" +
                "ag jf\n" +
                "nj lb\n" +
                "dl da\n" +
                "fm cl\n" +
                "dl lh\n" +
                "ef me\n" +
                "ib lm\n" +
                "eb ik\n" +
                "hl cc\n" +
                "ge be\n" +
                "nf dj\n" +
                "ba ff\n" +
                "li kc\n" +
                "ne ha\n" +
                "ef mf\n" +
                "gb bg\n" +
                "lh ia\n" +
                "jd cd\n" +
                "ha lj\n" +
                "ag mi\n" +
                "ac jk\n" +
                "eg kl\n" +
                "lb ci\n" +
                "dg ae\n" +
                "nc ca\n" +
                "gk bj\n" +
                "ka cl\n" +
                "gm dj\n" +
                "al de\n" +
                "dn nf\n" +
                "aa nn\n" +
                "gd db\n" +
                "fb be\n" +
                "ln lj\n" +
                "lk gg\n" +
                "ia nd\n" +
                "le fj\n" +
                "dl am\n" +
                "ja lb\n" +
                "dc da\n" +
                "db eh\n" +
                "mj cn\n" +
                "fa dj\n" +
                "ab kn\n" +
                "de gl\n" +
                "ch jg\n" +
                "fi fl\n" +
                "ln jh\n" +
                "mc am\n" +
                "jm lk\n" +
                "mn da\n" +
                "me mm\n" +
                "jd hb\n" +
                "il fj\n" +
                "fc gn\n" +
                "ne ga\n" +
                "fi nk\n" +
                "hi ga\n" +
                "hl bd\n" +
                "bh ae\n" +
                "kl fi\n" +
                "ii de\n" +
                "ig cl\n" +
                "lj kh\n" +
                "bi dc\n" +
                "cb cg\n" +
                "mk kh\n" +
                "bb lm\n" +
                "mk gm\n" +
                "ea ae\n" +
                "hj nm\n" +
                "ch dc\n" +
                "nc ce\n" +
                "ec ib\n" +
                "kc ga\n" +
                "dd mm\n" +
                "ni kb\n" +
                "hc db\n" +
                "ma na\n" +
                "hc am\n" +
                "ej ae\n" +
                "lk fg\n" +
                "mb fi\n" +
                "ea gb\n" +
                "gd ab\n" +
                "dn cn\n" +
                "aj ln\n" +
                "lm mf\n" +
                "fn ka\n" +
                "jh ed\n" +
                "jn jf\n" +
                "le gl\n" +
                "hn nd\n" +
                "lk bj\n" +
                "gg ij\n" +
                "di ab\n" +
                "ie ni\n" +
                "le lb\n" +
                "dl he\n" +
                "cn ca\n" +
                "kd ch\n" +
                "nj ch\n" +
                "bb cf\n" +
                "je he\n" +
                "ii nb\n" +
                "ng be\n" +
                "bg ga\n" +
                "dd bd\n" +
                "ej ja\n" +
                "ei fb\n" +
                "hm he\n" +
                "cf ga\n" +
                "md cj\n" +
                "hd lj\n" +
                "ki ji\n" +
                "jf kn\n" +
                "md ln\n" +
                "jg bb\n" +
                "cl fc\n" +
                "bc cc\n" +
                "dg ll\n" +
                "kn gk\n" +
                "ib fe\n" +
                "el bb\n" +
                "aa nc\n" +
                "eg dh\n" +
                "cj hg\n" +
                "kc gd\n" +
                "ie an\n" +
                "dn kc\n" +
                "ag gj\n" +
                "di je\n" +
                "gg eb\n" +
                "kn gk\n" +
                "ig am\n" +
                "in bc\n" +
                "bk cb\n" +
                "ji dd\n" +
                "mh mh\n" +
                "nl jn\n" +
                "de af\n" +
                "dn bm\n" +
                "gk kj\n" +
                "ha mm\n" +
                "ib lj\n" +
                "ji mb\n" +
                "ab if\n" +
                "mc en\n" +
                "ge fa\n" +
                "eg mj\n" +
                "cc ei\n" +
                "ac ek\n" +
                "bb dg\n" +
                "hn hi\n" +
                "ad nh\n" +
                "fi fn\n" +
                "mj ll\n" +
                "bi ea\n" +
                "jl ic\n" +
                "nn mh\n" +
                "ah aa\n" +
                "hh if\n" +
                "ic nf\n" +
                "kb el\n" +
                "ik gi\n" +
                "cb jk\n" +
                "mi ml\n" +
                "hf fj\n" +
                "kn hf\n" +
                "eh kb\n" +
                "hl hm\n" +
                "lb jd\n" +
                "ld kf\n" +
                "ej na\n" +
                "ba jb\n" +
                "dc ig\n" +
                "be ja\n" +
                "li be\n" +
                "ek cd\n" +
                "lc gn\n" +
                "fa ch\n" +
                "jm fi\n" +
                "nb hj\n" +
                "bl ba\n" +
                "na ab\n" +
                "gf fk\n" +
                "be ni\n" +
                "gi hl\n" +
                "ih ck\n" +
                "dj cb\n" +
                "kk kc\n" +
                "fn bm\n" +
                "nc le\n" +
                "hk me\n" +
                "ae mj\n" +
                "mg ee\n" +
                "la mg\n" +
                "jc ha\n" +
                "mc bg\n" +
                "bn cb\n" +
                "nb dn\n" +
                "ln dg\n" +
                "dd nj\n" +
                "hk mb\n" +
                "ln he\n" +
                "be fg\n" +
                "gk kl\n" +
                "hn kf\n" +
                "af eg\n" +
                "fk lk\n" +
                "mb di\n" +
                "kn if\n" +
                "mn ih\n" +
                "di nl\n" +
                "ec ih\n" +
                "bb mk\n" +
                "gn ca\n" +
                "il ij\n" +
                "lk ce\n" +
                "jb hh\n" +
                "ml ag\n" +
                "dk db\n" +
                "md gg\n" +
                "ee cm\n" +
                "cg mi\n" +
                "bg ei\n" +
                "af mk\n" +
                "hb dh\n" +
                "lb ld\n" +
                "jj dm\n" +
                "mg ef\n" +
                "jn bc\n" +
                "dn ll\n" +
                "db dd\n" +
                "eb nd\n" +
                "ag ij\n" +
                "fc nj\n" +
                "lm im\n" +
                "df di\n" +
                "cf km\n" +
                "ck he\n" +
                "jc ff\n" +
                "db gn\n" +
                "hg jc\n" +
                "id jk\n" +
                "aj id\n" +
                "ag lb\n" +
                "je nb\n" +
                "mi dm\n" +
                "kk dh\n" +
                "jn gm\n" +
                "fj aa\n" +
                "le kn\n" +
                "nm dj\n" +
                "eh km\n" +
                "ja la\n" +
                "in mh\n" +
                "he ac\n" +
                "em ac\n" +
                "gk aj\n" +
                "mi hd\n" +
                "gg kk\n" +
                "ld il\n" +
                "df jg\n" +
                "en nj\n" +
                "dm lk\n" +
                "kl kf\n" +
                "fg ba\n" +
                "al de\n" +
                "dg ag\n" +
                "hi bm\n" +
                "nd ek\n" +
                "aa fc\n" +
                "mi mc\n" +
                "di hh\n" +
                "mj hj\n" +
                "gj lm\n" +
                "nc di\n" +
                "lj gg\n" +
                "mf ck\n" +
                "fi ml\n" +
                "bg nc\n" +
                "nm he\n" +
                "fi ll\n" +
                "dl ik\n" +
                "ni cc\n" +
                "di ik\n" +
                "ld fa\n" +
                "ki ld\n" +
                "ai dl\n" +
                "en bn\n" +
                "fd jk\n" +
                "ai gj\n" +
                "ac jl\n" +
                "kl gc\n" +
                "mj ai\n" +
                "dk ji\n" +
                "ch fd\n" +
                "ei bg\n" +
                "lg cj\n" +
                "mm cj\n" +
                "mm gn\n" +
                "hn ng\n" +
                "gh ag\n" +
                "bg aj\n" +
                "lj kd\n" +
                "dk kb\n" +
                "dj im\n" +
                "fm hn\n" +
                "ij kd\n" +
                "gi jc\n" +
                "ni im\n" +
                "ac fb\n" +
                "jk cj\n" +
                "fd in\n" +
                "md lg\n" +
                "bc fb\n" +
                "jn ej\n" +
                "fd jc\n" +
                "me mf\n" +
                "ee ek\n" +
                "ba gn\n" +
                "bi kg\n" +
                "jd ml\n" +
                "da mk\n" +
                "mn dn\n" +
                "cl bd\n" +
                "nk gm\n" +
                "bn hd\n" +
                "ll ba\n" +
                "dc el\n" +
                "df im\n" +
                "fk gf\n" +
                "hd ed\n" +
                "al hh\n" +
                "il em\n" +
                "ic bh\n" +
                "mj ff\n" +
                "jj cb\n" +
                "ae mk\n" +
                "md bf\n" +
                "ga jf\n" +
                "jb lf\n" +
                "mc dd\n" +
                "dn ig\n" +
                "gk jb\n" +
                "fm ab\n" +
                "bj kf\n" +
                "nb in\n" +
                "na dd\n" +
                "nh gj\n" +
                "kf kl\n" +
                "ci bl\n" +
                "ek mh\n" +
                "jc gj\n" +
                "mh mk\n" +
                "ik hl\n" +
                "if mi\n" +
                "mn dh\n" +
                "cd ci\n" +
                "mb fd\n" +
                "mc ka\n" +
                "di kf\n" +
                "be nb\n" +
                "bi ki\n" +
                "ld ch\n" +
                "cb nk\n" +
                "dg cd\n" +
                "fa gn\n" +
                "ch nb\n" +
                "cd gd\n" +
                "im eb\n" +
                "fj hh\n" +
                "ml mc\n" +
                "nl kn\n" +
                "de aa\n" +
                "em ni\n" +
                "em ie\n" +
                "cm ig\n" +
                "jn fi\n" +
                "gl bm\n" +
                "jj ad\n" +
                "ga ai\n" +
                "ef gh\n" +
                "bh ni\n" +
                "gg mf\n" +
                "dn jg\n" +
                "kn ak\n" +
                "kg ic\n" +
                "bd ff\n" +
                "dd lf\n" +
                "gm mf\n" +
                "di li\n" +
                "mh lj\n" +
                "en bn\n" +
                "mb ja\n" +
                "ig aj\n" +
                "hk mh\n" +
                "lj nl\n" +
                "hm ae\n" +
                "gh kj\n" +
                "me ee\n" +
                "dl ea\n" +
                "nb ac\n" +
                "fh jh\n" +
                "bl am\n" +
                "hi hl\n" +
                "eh nm\n" +
                "ak hk\n" +
                "aa ml\n" +
                "mk jb\n" +
                "jk bl\n" +
                "ca ca\n" +
                "kc kb\n" +
                "ij kd\n" +
                "cf nm\n" +
                "bc gb\n" +
                "df kn\n" +
                "na mn\n" +
                "ik ii\n" +
                "ib gi\n" +
                "dg ke\n" +
                "af hl\n" +
                "kn ja\n" +
                "bl bj\n" +
                "bg ic\n" +
                "gj ba\n" +
                "fn jn\n" +
                "ab ha\n" +
                "gi cd\n" +
                "nh ag\n" +
                "eg gj\n" +
                "bk eg\n" +
                "ak ic\n" +
                "dk df\n" +
                "jl eh\n" +
                "nh fk\n" +
                "bk lf\n" +
                "bn ja\n" +
                "fj hg\n" +
                "de mh\n" +
                "mk je\n" +
                "en jc\n" +
                "ia jm"));
//        Scanner s = new Scanner(new File("D:/input03.txt"));
        int t = s.nextInt();
        String[] pair_left = new String[t];
        String[] pair_right = new String[t];

        for (int i = 0; i < t; i++) {
            pair_left[i] = s.next();
            pair_right[i] = s.next();
        }

        Set<String> setLeft = new HashSet<>();
        Set<String> setRight = new HashSet<>();
        int count = 0;
        for (int i = 0; i < pair_left.length; i++) {
            final boolean addLeft = setLeft.add(pair_left[i]);
            final boolean addRight = setRight.add(pair_right[i]);
            final boolean concatenado = setLeft.add(pair_left[i] + pair_right[i]);

            if (addLeft && addRight) {
                count++;
                System.out.println(count);
            }else if(addLeft || addRight) {
                count++;
                System.out.println(count);
            }else if(concatenado) {
                count++;
                System.out.println(count);
            }else {
                System.out.println(count);
            }
        }
    }
}